### ISSUE TITLE
F-resilient Write quorums for the Uniform strategy method

### ISSUE THREAD

**Issue by samueleresca** [mwhittaker/quorums#8]
Hi @mwhittaker,

I see the following implementation for the `uniform_strategy` method:

```
def uniform_strategy(self, f: int = 0) -> 'Strategy[T]':
  ...
  xs = list(self.elements())            
  read_quorums = list(self._f_resilient_quorums(f, xs, self.reads))            
  write_quorums = list(self._f_resilient_quorums(f, xs, self.reads))
  ...
```
([line 179](https://github.com/mwhittaker/quoracle/blob/d83a811a905a51fc13ebc00ddac036d559463380/quoracle/quorum_system.py#L179))

Am I right to suppose that in the `f_resilient_quorums` call for the `write_quorums` var, it should pass the `self.writes` property of the quorum system?

Thanks 😄

**Comment by mwhittaker** [comment]
Haha whoops! Yeah, that is a bug. Just pushed a commit to fix it. Thanks so much for finding the bug Samuele. If you find any other bugs, definitely let me know!
